### ISSUE TITLE
Training Rainnet

### ISSUE THREAD

**Issue by gs7776** [hydrogo/rainnet#1]
Hi Georgy, I am a student at Stanford taking course CS231 on CNNs. Found your Rainnet project very interesting and decided to replicate it as part of my course project. 
I have trouble making it train from scratch, using my data (initially moving MNIST). Is it possible to share the remaining code that relates to the training of the model?  
Many thanks, Georgios.
gs7776 at stanford.edu

**Comment by Eyal-Hashim** [comment]
Hello Georgy,
This project looks very interesting, I am also interested in training the model from scratch for a class mini-project. It will be nice to get some idea how to compile and fit the model.
all the best!
Eyal
