### ISSUE TITLE
issues defining input size/shape

### ISSUE THREAD

**Issue by sarahvigoureux** [hydrogo/rainnet#15]
Hello, 

I don't understand how you define the input size in rainnet. Actually when we look at the RYDL data, they are 900 x 900 arrays, but you set the argument input_shape=(928, 928, 4) so I don't understand.
Besides I try to make forecasts from other rain maps of size 224x224 and I have errors when I execute model.fit

Can you help me to understand how to define the size of the data or tell me what elements to modify in the algorithm when changing the size of the data please?

Thank you

**Comment by hydrogo** [comment]
Hi @sarahvigoureux,
Thank you for your interest in rainnet. The spatial shape of 928x928 is a prerequisite for the U-net-type architecture, where the spatial extent of input data has to be a multiple of 2**(n+1), where n is the number of max pooling layers (4 in the case of rainnet). In this way, technically, 224x224 inputs should pass. What kind of errors do you have? Training model from scratch is complicated and annoying: one should control everything from the data side: shapes, presence of nans, appropriate scaling, I/O bottlenecks, etc. Did you try the code provided in the examples folder by @PradyumnaGupta?

**Comment by sarahvigoureux** [comment]
Hi @hydrogo, *thank you very much for you answer. I managed to solve the error when training the algorithm by deleting the maps without rain (with only 0). You did the same thing in your training dataset?
In this case how does the model knows the next map is not the one 5 min after but more ? is the model able to learn it from the names/keys associated to rainfall maps?

**Comment by sarahvigoureux** [comment]
Furthemore, the prediction I get are strange... In your article (and others) i read about the vanishing gradient issue, but in my prediction I have isolated pixels whose intensities evolve over time, and moreover the rain field does not move at all in the different images (please see the 2 animated plots associated, or you can download them here : https://filesender.renater.fr/?s=download&token=5a14ef8e-2500-4030-9801-8c0893516b9b)
![expected-prediction](https://user-images.githubusercontent.com/114163264/194893774-13dd0c24-65df-4e2b-a7a8-d84ab8b53184.gif)
![rainnet-prediction](https://user-images.githubusercontent.com/114163264/194893776-531d8d7b-1b86-4a5c-9235-b2cf063144ba.gif)

**Comment by sarahvigoureux** [comment]
I have an additionnal issue : on my prediction rainfall only increase (quite exponentially) and do not decrease. You can see it on the plot associated, crosses = RainNet, squares = expected rainfall). Do you have an idea why it behaves like this ?

Thank you very much for your help.
![image](https://user-images.githubusercontent.com/114163264/194905734-0a8b71d6-3d53-4062-958c-56ba16ea509e.png)

**Comment by sarahvigoureux** [comment]
I have an additionnal issue : on my prediction rainfall only increase (quite exponentially) and do not decrease. You can see it on the plot associated, crosses = RainNet, circles= expected rainfall). Do you have an idea why it behaves like this ?

![image](https://user-images.githubusercontent.com/114163264/194906161-ee0c138a-469c-496b-ae8f-fb722e5d0777.png)

Thank you very much for your help.
