### ISSUE TITLE
Datasheet

### ISSUE THREAD

**Issue by a5782** [hydrogo/rainnet#3]
Sir ..I was unable to view the datasheet ..it showing that the file can't open..which software I need to open the file sir

**Comment by hydrogo** [comment]
Hi @a5782 ,
Are you talking about radar data (RY reanalysis) that we used for training and evaluation? It is available here https://zenodo.org/record/3629951#.X460v5qxUvg as a single .hdf5 file. You can use `h5py` Python library to read the respective dataset.
Hope this helps.

Best regards,
Georgy

**Comment by a5782** [comment]
Thanks a lot sir
