### ISSUE TITLE
Regarding RYproduct dataset 

### ISSUE THREAD

**Issue by PradyumnaGupta** [hydrogo/rainnet#7]
Can you please explain a bit about how did you use the RYproduct dataset which you have mentioned in the readme? The zenodo link in the readme points to an hdf5 file which just contains the images. I would be grateful if could tell me how did you divided those images for training , into inputs and targets . 
Thanks.

**Comment by PradyumnaGupta** [comment]
@hydrogo

**Comment by hydrogo** [comment]
Hi @PradyumnaGupta,
thanks for your interest in RainNet. For training, we use the complete RY product, that has been provided to us by the German Weather Sevice (DWD). We used data from 2006 to 2013 to optimize RainNet's model parameters. 

The readme contains only the data sample that you can use for the evaluation of Rainnet. Operational data is also available at DWD's open data portal: https://opendata.dwd.de/weather/radar/radolan/ry/. You can find the radar data documentation here: https://www.dwd.de/DE/leistungen/radolan/radolan.html

All the best,
Georgy

**Comment by PradyumnaGupta** [comment]
Hello there, thanks for the reply. However, the dataset link given by you ([https://opendata.dwd.de/weather/radar/radolan/ry/](https://opendata.dwd.de/weather/radar/radolan/ry/)) only contains the files related to last two days and not from 2006-2013 . Can you please clarify a bit on how to obtain the bigger dataset and also how to open the --bin files in that link ? 
Thanks .
